name = "HTMLParser"
uuid = "b4b65fde-acad-11e9-1657-e5fb27898dff"
authors = ["Matt Lawless"]
version = "0.1.0"

[compat]
julia = "^1"

[deps]

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
